version: "3.8"

services:
  database-postgres:
    image: postgres:12.3
    container_name: postgres
    restart: always 
    environment:
      POSTGRES_DB: 'core'
      POSTGRES_USER: 'postgres_user'
      POSTGRES_PASSWORD: 'postgres_pass'
    ports:
      - "5432:5432"